markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

excerpt_separator: <!--more--> # you can specify your own separator, of course.

paginate: 8
paginate_path: "page:num"

# presonal config
domain: 
title: ec-cwang's Blog
description: Java Web, Linux, Reading...
author: ec-cwang
email: 
github: ec-cwang

config:
  js_dir:
  img_dir:
  css_dir:
